// This file is provided under The MIT License as part of Steamworks.NET.
// Copyright (c) 2013-2019 Riley Labrecque
// Please see the included LICENSE.txt for additional information.

// This file is automatically generated.
// Changes to this file will be reverted when you update Steamworks.NET

#if UNITY_ANDROID || UNITY_IOS || UNITY_TIZEN || UNITY_TVOS || UNITY_WEBGL || UNITY_WSA || UNITY_PS4 || UNITY_WII || UNITY_XBOXONE || UNITY_SWITCH
#define DISABLESTEAMWORKS
#endif

#if !DISABLESTEAMWORKS


namespace Steamworks {
    [System.Serializable]
    public struct SteamItemDef_t : System.IEquatable<SteamItemDef_t>, System.IComparable<SteamItemDef_t> {
        public int m_SteamItemDef;

        public SteamItemDef_t(int value) => this.m_SteamItemDef = value;

        public override string ToString() => this.m_SteamItemDef.ToString();

        public override bool Equals(object other) => other is SteamItemDef_t && this == (SteamItemDef_t)other;

        public override int GetHashCode() => this.m_SteamItemDef.GetHashCode();

        public static bool operator ==(SteamItemDef_t x, SteamItemDef_t y) => x.m_SteamItemDef == y.m_SteamItemDef;

        public static bool operator !=(SteamItemDef_t x, SteamItemDef_t y) => !(x == y);

        public static explicit operator SteamItemDef_t(int value) => new SteamItemDef_t(value);

        public static explicit operator int(SteamItemDef_t that) => that.m_SteamItemDef;

        public bool Equals(SteamItemDef_t other) => this.m_SteamItemDef == other.m_SteamItemDef;

        public int CompareTo(SteamItemDef_t other) => this.m_SteamItemDef.CompareTo(other.m_SteamItemDef);
    }
}

#endif // !DISABLESTEAMWORKS
