// This file is provided under The MIT License as part of Steamworks.NET.
// Copyright (c) 2013-2019 Riley Labrecque
// Please see the included LICENSE.txt for additional information.

// This file is automatically generated.
// Changes to this file will be reverted when you update Steamworks.NET

#if UNITY_ANDROID || UNITY_IOS || UNITY_TIZEN || UNITY_TVOS || UNITY_WEBGL || UNITY_WSA || UNITY_PS4 || UNITY_WII || UNITY_XBOXONE || UNITY_SWITCH
#define DISABLESTEAMWORKS
#endif

#if !DISABLESTEAMWORKS

namespace Steamworks {
    [System.Serializable]
    public struct PublishedFileUpdateHandle_t : System.IEquatable<PublishedFileUpdateHandle_t>, System.IComparable<PublishedFileUpdateHandle_t> {
        public static readonly PublishedFileUpdateHandle_t Invalid = new PublishedFileUpdateHandle_t(0xffffffffffffffff);
        public ulong m_PublishedFileUpdateHandle;

        public PublishedFileUpdateHandle_t(ulong value) => this.m_PublishedFileUpdateHandle = value;

        public override string ToString() => this.m_PublishedFileUpdateHandle.ToString();

        public override bool Equals(object other) => other is PublishedFileUpdateHandle_t && this == (PublishedFileUpdateHandle_t)other;

        public override int GetHashCode() => this.m_PublishedFileUpdateHandle.GetHashCode();

        public static bool operator ==(PublishedFileUpdateHandle_t x, PublishedFileUpdateHandle_t y) => x.m_PublishedFileUpdateHandle == y.m_PublishedFileUpdateHandle;

        public static bool operator !=(PublishedFileUpdateHandle_t x, PublishedFileUpdateHandle_t y) => !(x == y);

        public static explicit operator PublishedFileUpdateHandle_t(ulong value) => new PublishedFileUpdateHandle_t(value);

        public static explicit operator ulong(PublishedFileUpdateHandle_t that) => that.m_PublishedFileUpdateHandle;

        public bool Equals(PublishedFileUpdateHandle_t other) => this.m_PublishedFileUpdateHandle == other.m_PublishedFileUpdateHandle;

        public int CompareTo(PublishedFileUpdateHandle_t other) => this.m_PublishedFileUpdateHandle.CompareTo(other.m_PublishedFileUpdateHandle);
    }
}

#endif // !DISABLESTEAMWORKS
